// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uzrtuuuitffeyhfsdgpj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6cnR1dXVpdGZmZXloZnNkZ3BqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk2NDI3NzcsImV4cCI6MjA3NTIxODc3N30.E4JtLXgTgrZ-R6sb_R-WUAWMMWpGH15O3NGsgdkg8lo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});